language: java
jdk:
- openjdk8
script: ant build


addons:
  sonarcloud:
    organization: "riccardoburaioli" 
    token: "81483b8ed77ad7807523a8157bcb8bcecc4f217b"

script:
- ant build
- sonar-scanner
